name: CLA Assistant
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
  push: # TODO
    branches:
      - vijay/oss

jobs:
  cla:
    name: CLA Assistant
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.4.0
        id: allowlist
        with:
          route: GET /repos/{repo}/collaborators
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.CLA_ASSISTANT_PERSONAL_ACCESS_TOKEN }}
      - run: echo '${{ join(fromJson(steps.allowlist.outputs.data).*.login) }}'
      - name: CLA Assistant
        if: github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT_PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-document: https://github.com/osohq/cla/blob/main/individual.md
          remote-organization-name: osohq
          remote-repository-name: cla-signatures
          path-to-signatures: individual.json
          branch: main
          allowlist: ${{ join(fromJson(steps.allowlist.outputs.data).*.login) }}
          use-dco-flag: false
          create-file-commit-message: "Creating file for storing CLA signatures"
          signed-commit-message: "$contributorName has signed the CLA in osohq/oso#$pullRequestNo"
          custom-notsigned-prcomment: "Thank you for your submission! Before we can accept your contribution, we ask that you sign our [Contributor License Agreement](https://github.com/osohq/cla/blob/main/individual.md). To sign the CLA, post a comment on this Pull Request that matches the following text ***exactly***:"
