name: Publish to PyPI
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v3
      - run: poetry build
      - name: Ensure changelog entry exists
        run: grep $(poetry version -s) CHANGELOG.md
      - id: version
        run: echo "v=$(poetry version -s)" >> $GITHUB_OUTPUT
      - id: version_fragment
        run: echo "v=$(poetry version -s | sed 's/\.//g')" >> $GITHUB_OUTPUT
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.v }}
          release_name: v${{ steps.version.outputs.v }}
          body: "[Changelog entry](${{ github.server_url }}/${{ github.repository }}/blob/main/CHANGELOG.md#v${{ steps.version_fragment.outputs.v }})"
      - uses: pypa/gh-action-pypi-publish@release/v1
